### PR TITLE
Adding MS/TP support

### PR DESCRIPTION
**Pull request by WhittlesJr**
This seems to be working with BACnet4J 4.0.1. I haven't tested absolutely everything but it seems to "just work." 

So you may or may not like the changes I made to the documentation (with the config param table) and the way I chose to do the configuration interface for MSTP (serial params in the main config map with an :mstp-config sub-map.) Of course that's up to you to accept or ask for changes, but this is what I arrived upon after some thought and experimentation. 

Originally I had all the params in the one flat config map, but it got a little verbose adding prefixes like "mstp-" to every key and such. And without those, things seemed a bit ambiguous. 

Oh, you also may or may not like the logging / debugging facilities I threw in there. They were helpful for me while developing this but I'm not sure if an end user would want them. I'd think it would be better to leave them in since they're fairly harmless, but you might think differently. 

Let me know what you think!

### CODE REVIEW

**Comment by Frozenlock** [comment]
Whoah, looks like you've done quite a bit of work.
I'm a little busy these days, but I'll take a look as soon as I can.

Thank you very much!

**Comment by WhittlesJr** [comment]
I'm happy to contribute! I hope the quality is acceptable... I'm still relatively new to Clojure, and quite new to BACnet. Suggestions appreciated.

**Comment by WhittlesJr** [comment]
Oh, I should also mention the addition of /dev/user.clj. It was helpful to have those requires auto-loaded in the REPL, but it may or may not be appropriate for the public repo.

**Comment by Frozenlock** [comment]
My tests are far from covering everything they should, but everything is still working. :smile: 

Amazing work!

**Comment by Frozenlock** [comment]
Btw, I just noticed a recent push for BACnet4J; is it affecting your code?

https://github.com/infiniteautomation/BACnet4J/commit/939757e7f2fb3110adf9d06753b7b82643adfba1

**Comment by WhittlesJr** [comment]
Thanks! I'm glad my work was helpful.

I haven't dug through everything in that push, but I doubt it'll affect us.
We're using a different serial implementation, not their wrapper. I'll look
into it tomorrow!

**Pull request merged**
