### PR TITLE
WhoIs/IAm + WhoHas/IHave + refactoring state management + event listening architecture

### PR DESCRIPTION
**Pull request by WhittlesJr**
OK, I touched a lot of lines here. A lot of it is just formatting though.

Here's a summary:
  - WhoHas/WhoIs: I added these under a new `bacure.services` NS, where also COV subscription will go when I do that next. These simply send the requests and have nothing to do with listening for responses.
  - IHave/IAm: I added these under a new `bacure.events` NS. *This* is what listens for events, and updates a stateful cache of what we find, under the local device that sent the request. (So the local-device has an event listener attached to it, and it stores what it gets from those events under the local-device atom.)
  - State management: I had to move the local-devices atom to a separate NS, so that there would not be a circular dependency between `bacure.local-device` and `bacure.events`. 
    - Because of this, I decided I might as well make the NS I move it to meaningful, so I added generic state-management methods that have a bit of intelligence built into them. For example, the notion of "if the device-id is nil, use the first local-device in the map" has been genericized for use by any hash-map atom. 
    - Since I decided to call the NS just "state," and I had all those generic methods, I decided I might as well move the other state atoms in there (serial-connections and the renamed "request-response"). I added access methods for these using those same generic state methods, and updated all uses of reset! or swap! in our code to use those accessors. 
  - One point you might want to change is how RemoteObjects are coerced and cached... I decided to mimic how other objects are coerced (maps of properties), with :object-name and :object-identifier being the only properties given. And when I cached them, I cached them a bit deeply, like below.
    - We could probably make that a bit more terse, but it would no longer look like a typical object. I dunno. Up to you.
```
{:remote-objects {<device-id-1> {[:analog-value 3]
                                 {:object-identifier [:analog-value 3],
                                  :object-name "5011_1"}},

                  <device-id-2> {[:analog-value 3]
                                 {:object-identifier [:analog-value 3],
                                  :object-name "5011_1"}}}}
```

I think on the whole, what I've ended up with is coherent and sensible, but that might not be the case from someone else's perspective.

### CODE REVIEW

**Comment by Frozenlock** [comment]
Amazing work!
I'll look at it immediately.

**Comment by Frozenlock** [comment]
FYI I think `bacure.util` is no longer necessary in `bacure.remote-device`. :stuck_out_tongue:

**Comment by Frozenlock** [comment]
Checked, fixed and tested.
Thank you very much!

**Comment by WhittlesJr** [comment]
Excellent, thank you! Glad to help.

**Pull request merged**
